import { CalendarClock, FileText, MessageSquareText, Phone, Timer } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../app/AuthProvider'
import { useWorkspace } from '../app/Workspace'
import { useData } from '../app/useData'
import { Empty, LeadCard, StateView } from '../components/ui'
import { params, type Lead } from '../services/api'

const choices=[['All','All'],['Reply','Needs reply'],['Call','Call today'],['Follow-up','Follow-up due'],['Estimate','Estimate waiting'],['Later','Waiting for client']]
const attentionKey:Record<string,string>={'Needs reply':'needs_reply','Call today':'call_today','Follow-up due':'follow_up_due','Estimate waiting':'estimate_waiting','Waiting for client':'waiting_for_client'}
type TodayPayload={items:Lead[];counts:Record<string,number>;total:number;readLocked?:boolean;mappingMissing?:boolean}
export default function Today(){const {profile}=useAuth(),workspace=useWorkspace(),navigate=useNavigate(),[filter,setFilter]=useState('All');const {data,loading,error}=useData<TodayPayload>('/today?'+params({brand:workspace==='All'?'':workspace,attention:attentionKey[filter]}));const selected=data?.items||[]
 const cards=[{label:'Needs reply',icon:MessageSquareText,filter:'Needs reply',tone:'lime'},{label:'Call today',icon:Phone,filter:'Call today'},{label:'Follow-ups',icon:Timer,filter:'Follow-up due'},{label:'Estimates waiting',icon:FileText,filter:'Estimate waiting'}]
 return <div className="page-wrap page-wrap--today"><div className="page-intro page-intro--split"><div><div className="eyebrow eyebrow--lime">{workspace==='All'?'WallPanels + Verona Home':workspace}</div><h1>Good morning, {profile?.full_name.split(' ')[0]||'there'}</h1><p>Here’s what needs your attention today.</p></div><div className="date-chip"><CalendarClock size={15}/>{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date())}</div></div><div className="metrics-grid">{cards.map(({label,icon:Icon,filter:value,tone})=><button className={`metric-card metric-card--${tone||'white'}`} onClick={()=>setFilter(value)} key={label}><div className="metric-top"><span>{label}</span><Icon size={17}/></div><strong>{data?.counts[attentionKey[value]]||0}</strong><small>Assigned to you</small><div className="metric-shape"/></button>)}</div><div className="section-heading-row"><div className="section-title"><div><span className="eyebrow">Start here</span><h2>Your priority queue</h2><p>A short list of the next best moves.</p></div></div><button className="btn btn--ghost" onClick={()=>navigate('/leads')}>View all leads →</button></div><div className="chip-row">{choices.map(([key,label])=><button key={key} className={`filter-chip ${filter===label?'is-active':''}`} onClick={()=>setFilter(label)}>{key}</button>)}</div><StateView loading={loading} error={error} empty={!loading&&selected.length===0}><div className="lead-card-grid">{selected.slice(0,4).map(l=><LeadCard key={`${l.locationId}:${l.id}`} lead={l} onAction={()=>navigate(`/leads/${l.locationId}/${l.opportunityId}`)}/>)}</div></StateView>{data?.readLocked&&<Empty title="Live CRM reading is locked" detail="Your administrator can enable read access after the safe-mode review."/>}{data?.mappingMissing&&<Empty title="CRM account not connected" detail="Your administrator must map your HighLevel user ID for this location."/>}</div>
}
