import { Link } from 'react-router-dom'
import { ArrowUpRight, CheckCircle2, Inbox, X, type LucideIcon } from 'lucide-react'
import type { ReactNode } from 'react'
import { attentionLabel, leadPath, type Lead } from '../services/api'
export const cn=(...parts:(string|false|null|undefined)[])=>parts.filter(Boolean).join(' ')
export function BrandMark(){return <div className="brand-lockup"><div className="brand-mark" aria-hidden="true"><span/><span/><span/></div><div><strong>wallpanels</strong><small>sales copilot</small></div></div>}
export function Avatar({name,color='#E5F7D7'}:{name:string;color?:string}){return <span className="avatar avatar--md" style={{background:color}}>{name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span>}
export function Pill({children,tone='quiet'}:{children:ReactNode;tone?:string}){return <span className={cn('pill',`pill--${tone}`)}>{children}</span>}
export function Button({children,onClick,variant='secondary',disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;variant?:string;disabled?:boolean;type?:'button'|'submit'}){return <button className={cn('btn',`btn--${variant}`)} onClick={onClick} disabled={disabled} type={type}>{children}</button>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button></div><div className="modal-body">{children}</div></div></div>}
export function Empty({title,detail,icon:Icon=Inbox}:{title:string;detail:string;icon?:LucideIcon}){return <div className="empty-state"><div className="empty-icon"><Icon size={20}/></div><h3>{title}</h3><p>{detail}</p></div>}
export function StateView({loading,error,empty,children}:{loading:boolean;error:string|null;empty?:boolean;children:ReactNode}){if(loading)return <div className="state-block"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/><p>Loading your workspace…</p></div>;if(error)return <Empty title="Workspace unavailable" detail="Please try again in a moment."/>;if(empty)return <Empty title="Nothing here yet" detail="There are no matching records in this view."/>;return <>{children}</>}
export function LeadCard({lead,onAction}:{lead:Lead;onAction?:()=>void}){return <article className="lead-card"><div className="lead-card-top"><Pill tone={lead.attention==='Needs reply'||lead.attention==='needs_reply'?'rose':'lime'}>{attentionLabel(lead.attention)}</Pill><span className="lead-time">{lead.lastInteraction}</span></div><div className="lead-main"><Avatar name={lead.contactName} color={lead.color}/><div><h3>{lead.company}</h3><p>{lead.contactName} · {lead.project||lead.pipeline}</p></div><Link className="icon-btn icon-btn--subtle" to={leadPath(lead)} aria-label={`Open ${lead.contactName}`}><ArrowUpRight size={18}/></Link></div><div className="lead-meta"><Pill>{lead.brand}</Pill><Pill>{lead.stage}</Pill><span>{lead.channel}</span></div><p className="lead-explanation">{lead.explanation}</p><div className="lead-card-footer"><div><span className="eyebrow">Recommended</span><strong>{lead.nextAction}</strong></div>{onAction&&<Button variant="primary" onClick={onAction}>Review</Button>}</div></article>}
export function Notice({children}:{children:ReactNode}){return <div className="safe-notice"><CheckCircle2 size={16}/>{children}</div>}
