import { Component, useEffect, useState, type ReactNode, type FormEvent } from 'react'
import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowLeft, Headphones, LayoutList, MessageSquareText, Search, Settings2, Sparkles } from 'lucide-react'
import { AuthProvider, useAuth } from './app/AuthProvider'
import { BrandMark, Empty } from './components/ui'
import { NotificationCenter } from './components/NotificationCenter'
import { WorkspaceScope, type Workspace } from './app/Workspace'
import { useData } from './app/useData'
import Today from './pages/Today'
import Leads from './pages/Leads'
import LeadWorkspace from './pages/LeadWorkspace'
import Conversations from './pages/Conversations'
import Calls from './pages/Calls'
import Preferences from './pages/Preferences'

class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<Empty title="This page could not load" detail="Please refresh the page or contact your administrator."/>:this.props.children}}
function Login(){const {signIn,error:configError}=useAuth(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate()
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);navigate('/today',{replace:true})}catch{setError('Sign in failed. Check your work email and password, or contact your administrator.')}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-grid"><section className="login-copy"><BrandMark/><div className="login-heading"><span className="pill pill--lime">Sales workspace</span><h1>Your sales day,<br/><em>already organized.</em></h1><p>Leads, conversations and next actions in one place.</p></div><div className="login-foot"><span>WallPanels + Verona Home</span><span>Company access</span></div></section><section className="login-panel"><div className="login-panel-inner"><div className="login-form-head"><span className="eyebrow">Welcome back</span><h2>Sign in to your workspace</h2><p>Use your company-provisioned account.</p></div><form onSubmit={e=>void submit(e)} className="form-stack"><label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{(error||configError)&&<p className="form-error" role="alert">{error||configError}</p>}<button className="btn btn--primary btn--full" type="submit" disabled={busy}>{busy?'Signing in…':'Sign in →'}</button></form><p className="login-help">Need access or a password reset? Contact your administrator.</p></div><div className="login-fragments" aria-hidden="true"><div className="fragment fragment--one"><span>NEXT ACTION</span><strong>Know who needs you.</strong><small>Focus on the right conversation</small></div><div className="fragment fragment--two"><span>SALES COPILOT</span><strong>One clear move.</strong><small>Grounded in customer context</small></div></div></section></div></div>
}
function Protected({children}:{children:ReactNode}){const {session,profile,loading,error}=useAuth();if(loading)return <div className="loading-screen">Loading your workspace…</div>;if(error)return <Empty title="Application unavailable" detail={error}/>;if(!session)return <Navigate to="/login" replace/>;if(!profile)return <Empty title="Account not connected" detail="Your CRM account is not connected yet. Please contact your administrator."/>;return <>{children}</>}
function Shell(){const {profile,config,signOut}=useAuth();const navigate=useNavigate();const [search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[menu,setMenu]=useState(false),[workspace,setWorkspace]=useState<Workspace>('All');const {data:preferences}=useData<{default_workspace:Workspace}>('/preferences');useEffect(()=>{if(preferences?.default_workspace)setWorkspace(preferences.default_workspace)},[preferences?.default_workspace])
 function doSearch(e:FormEvent){e.preventDefault();navigate(`/leads?search=${encodeURIComponent(search)}`);setSearchOpen(false)}
 return <div className="app-shell"><header className="app-header"><Link to="/today" className="header-left"><BrandMark/></Link><nav className="top-nav" aria-label="Primary navigation">{[{to:'/today',label:'Today',Icon:Sparkles},{to:'/leads',label:'My Leads',Icon:LayoutList},{to:'/conversations',label:'Conversations',Icon:MessageSquareText},{to:'/calls',label:'Calls',Icon:Headphones}].map(({to,label,Icon})=><NavLink key={to} to={to} className={({isActive})=>`nav-pill ${isActive?'is-active':''}`}><Icon size={15}/><span>{label}</span></NavLink>)}</nav><WorkspaceScope workspace={workspace}><div className="header-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={16}/><span>Search</span></button><NotificationCenter/><select className="workspace-select" aria-label="Workspace" value={workspace} onChange={e=>setWorkspace(e.target.value as Workspace)}><option>All</option><option>WallPanels</option><option>Verona Home</option></select>{config?.safeTestMode&&<span className="safe-mode">Safe mode</span>}<button className="profile-trigger" onClick={()=>setMenu(!menu)} aria-label="Account menu"><span className="avatar avatar--sm">{profile?.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span></button>{menu&&<div className="user-menu"><div className="user-menu-head"><strong>{profile?.full_name}</strong></div><button onClick={()=>{navigate('/preferences');setMenu(false)}}><Settings2 size={15}/> Preferences</button><button className="menu-danger" onClick={()=>void signOut()}><ArrowLeft size={15}/> Sign out</button></div>}</div></WorkspaceScope></header><WorkspaceScope workspace={workspace}><main className="app-main"><ErrorBoundary><Routes><Route path="/today" element={<Today/>}/><Route path="/leads" element={<Leads/>}/><Route path="/leads/:locationId/:opportunityId" element={<LeadWorkspace/>}/><Route path="/conversations" element={<Conversations/>}/><Route path="/conversations/:locationId/:conversationId" element={<Conversations/>}/><Route path="/calls" element={<Calls/>}/><Route path="/calls/:locationId/:messageId" element={<Calls/>}/><Route path="/preferences" element={<Preferences/>}/><Route path="*" element={<Navigate to="/today" replace/>}/></Routes></ErrorBoundary></main></WorkspaceScope>{searchOpen&&<div className="overlay overlay--search" onMouseDown={e=>e.target===e.currentTarget&&setSearchOpen(false)}><form className="command-palette" onSubmit={doSearch}><div className="command-input"><Search size={18}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads, companies, phone or email"/><button type="button" onClick={()=>setSearchOpen(false)}>Close</button></div><div className="command-footer">Press Enter to search assigned opportunities.</div></form></div>}</div>
}
function AppRoutes(){const {session}=useAuth();return <Routes><Route path="/login" element={session?<Navigate to="/today" replace/>:<Login/>}/><Route path="/*" element={<Protected><Shell/></Protected>}/></Routes>}
export default function App(){return <BrowserRouter><AuthProvider><AppRoutes/></AuthProvider></BrowserRouter>}
